baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 2

  [[menu.main]]
  name = "Project 1"
  url = "/portfolio/project1/"
  weight = 3

  [[menu.main]]
  name = "Skills"
  url = "/portfolio/skills/"
  weight = 4

  [[menu.main]]
  name = "Resume"
  url = "/portfolio/resume/"
  weight = 5

  [[menu.main]]
  name = "Contact"
  url = "/portfolio/contact/"
  weight = 6
